name: CI Java

on: 
  workflow_call

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.5.3
        # Seteo versión de Java (jdk necesario)
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: "zulu"
          java-version: "11"
        #  Compilando Proyecto Graddle a mano
      - name: Compile Graddle
        run: |
          chmod +x gradlew
          ./gradlew build
   

