name: CI Java

on: 
  workflow_call

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.5.3
        # Seteo versión de Java (jdk necesario)
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: "11"
        #  Compilando Proyecto Maven a mano
      - name: Compile Maven
        run: |
          chmod +x nvmw
          ./nvmw clean compile
   

