name: CI Java

on: 
  workflow_call

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Descarga Codigo
        run: ls -ltr

      - name: Hola Mundo
        run: echo "Hola Mundo desde devops-pipeline"
